#!/bin/sh
echo Defaults \!tty_tickets > $1          # Entering your password in one shell affects all shells 
echo Defaults timestamp_timeout=90 >> $1 # Time between re-requesting your password, in minutes
